services:
  - type: web
    name: pass-project
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate  # ✅ This line ensures migrations are run during build
    startCommand: gunicorn pass_project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: pass_project.settings
      - key: PYTHON_VERSION
        value: 3.11
