# Generated by Django 5.0.6 on 2025-07-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventPass',
        ),
    ]
