# Generated by Django 5.0.6 on 2025-07-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='venue',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
