# Generated by Django 5.0.6 on 2025-07-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0004_invoice_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
    ]
