# Generated by Django 5.0.6 on 2025-07-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0005_invoice_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], default='Cash', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=10),
        ),
    ]
