# Generated by Django 5.0.6 on 2025-07-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0006_invoice_payment_mode_invoice_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='venue',
            field=models.CharField(default='', max_length=200),
        ),
    ]
