# Generated by Django 5.0.6 on 2025-07-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passapp', '0007_alter_invoice_email_alter_invoice_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online'), ('Split', 'Split')], default='Cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Partially Paid', 'Partially Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=20),
        ),
    ]
